### ISSUE TITLE
http://shop.happycasts.net/

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#307]
做个静态网页，好看点的，真正要购买就去淘宝。
大概就是做一个 https://github.myshopify.com 

卖一些我们自己体验过的文具日用品等等。算是给大家做一个体验官。

**Comment by happypeter** [comment]
@billie66 淘宝店申请有进展了，可以来这里讨论。

**Comment by billie66** [comment]
好的

**Comment by happypeter** [comment]
备货不是太方便，暂时放弃吧。
