### ISSUE TITLE
打赏二维码

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#314]
@shooterman 是支付宝的打赏二维码？

**Comment by shooterman** [comment]
@happypeter  支付宝 微信 打赏都可以

**Comment by billie66** [comment]
http://chloerei.com/donate/ 有支付宝二维码

**Comment by billie66** [comment]
http://jingyan.baidu.com/article/6f2f55a1a7abcfb5b93e6cd9.html

**Comment by happypeter** [comment]
![code](https://cloud.githubusercontent.com/assets/72467/6749037/325d539a-cf27-11e4-91c4-976511b08ad8.png)

**Comment by billie66** [comment]
代码部署了

**Comment by happypeter** [comment]
thx
