### ISSUE TITLE
翻译国外优秀视频

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#316]
这个是 @shooterman 给的建议。我觉得不错，那么多优秀视频，很多朋友因为语言障碍看不了。

**Comment by shooterman** [comment]
https://www.youtube.com/watch?v=DGhlQomeqKc  理解了 30%  但也感觉很有收获  unix编程 是我所不熟悉的

**Comment by happypeter** [comment]
@shooterman  Unix Programming 倒是我当年的老本行，不过这个视频的内容对于网站开发整体用户来说太垂直了点，ruby&&unix&&server-admin


我想翻译一下：http://schacon.github.io/2008/06/02/railsconf-git-talk.html 这个演讲是对我自己影响极大的。不过我发现录视频总从我自己的喜好出发有时候观众是不买单的，你看看，感觉一下这个视频我要是翻译了会不会有人看，给我点反馈，多谢

或者你还有什么其他的推荐？

**Comment by shooterman** [comment]
Scot Chacon?!  cool  先从自己收益最大的开始吧 英文资料我关注的不多.
发布这个视频顺带可以做个调查, 放在公众号 或者 happycasts上

https://jinshuju.net/  http://www.mikecrm.com/

**Comment by happypeter** [comment]
:dancer:
