### ISSUE TITLE
申请了微信订阅号

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#317]
@shooterman 你扫扫看能用吗？

![qrcode_for_gh_352a443bf131_258](https://cloud.githubusercontent.com/assets/72467/6824865/d224e78c-d330-11e4-83e9-c93117c86222.jpg)

**Comment by happypeter** [comment]
刚刚给 MacTalk 赞赏了10元，确实很方便

**Comment by happypeter** [comment]
登陆 https://mp.weixin.qq.com 在 `素材管理` 一项下面写个个配图文章，但却不知道如何进行群发，郁闷中 》。。。

**Comment by happypeter** [comment]
@billie66 把这个二维码添加到网站页面底部吧，跟捐助类似的效果

**Comment by billie66** [comment]
好的
