### ISSUE TITLE
网站备案

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#318]
发现 github 最近不翻墙总是上不去，这样我的那些在 github pages 的书也一样是受到影响了。

所以如果 haoduoshipin.com 备案了，那么就可以在 haoduoshipin.com/book/book-name 下面来托管了。

**Comment by happypeter** [comment]
使用阿里云的备案服务就行

**Comment by billie66** [comment]
ok

**Comment by billie66** [comment]
阿里云首次备案流程

http://help.aliyun.com/knowledge_detail.htm?knowledgeId=5974924

**Comment by billie66** [comment]
如何获得阿里云备案服务号

http://help.aliyun.com/knowledge_detail.htm?knowledgeId=5975023

**Comment by happypeter** [comment]
按照上面获取服务号成功了

**Comment by happypeter** [comment]
> haoduoshipin.com 是王广忠个人的技术资料分享网站

如果要填网站性质就填这个

**Comment by billie66** [comment]
备案资料已经提交，等待初审

**Comment by happypeter** [comment]
阿里的客服来电话，说提交的资料有两个问题：

- 第一，审核通过前 haoduoshipin.com 是不能访问的，需要关闭网站
- 第二，网站名称中不能包含“视频”字样，域名中的 `shipin` 没关系

**Comment by happypeter** [comment]
刚刚我把  haoduoshipin.com 和 yikuaibing-art.com 的 DNS 都删了。过一会儿，再次提交申请吧

**Comment by happypeter** [comment]
网站名称改为，`好多诗品网` 吧

**Comment by happypeter** [comment]
过了，真快啊

**Comment by happypeter** [comment]
下一步提交材料，邮寄，需要拍照

**Comment by happypeter** [comment]
申请拍照幕布，和提交材料可以并行进行

**Comment by billie66** [comment]
审核资料已经邮寄，幕布收到且照片已经上传

**Comment by happypeter** [comment]
幕布照片，昨天就说审核通过了。今天又有短信，说收到了邮寄的材料，会在一两天内给出审核结果

**Comment by happypeter** [comment]
邮寄材料，阿里这边已经审核通过，下一步会交局审核

**Comment by billie66** [comment]
![screen shot 2015-04-03 at 1 42 05 pm](https://cloud.githubusercontent.com/assets/102444/6978576/fc9ded1e-da07-11e4-8dca-4dc23a91c4cf.png)

**Comment by happypeter** [comment]
下来了！！！

尊敬的王广忠：
 
	恭喜您，您的备案已经办理成功！
王广忠的备案（订单号：21320127111）已经通过省通信管理局审核！
请登录阿里云代备案系统查看您的备案号，并请您按照工信部规定，在您的网站首页底部中间位置，放置您的备案号并链接至"http://www.miitbeian.gov.cn/"。例如"京ICP备999999"（此备案号为例子，请您一定更换成自己的备案号）。
附工信部备案规定：非经营性互联网信息服务提供者应当在其网站开通时，在主页底部的中央位置标明其备案编号，并在备案编号下方按要求链接信息产业部备案管理系统网址，供公众查询核对。
 
备案成功后，您还可以：
1.增加新网站，登录阿里云代备案系统，在已成功备案信息下增加新的网站;
2.单位/个人信息或网站发生了变化，及时登录阿里云代备案系统，提交变更备案信息;
 
相关政策法规： 依据《非经营性互联网信息服务备案管理办法》第二十三条规定，如备案信息不真实，将关闭网站并注销备案。若您的备案信息发生变更，请您尽快将备案信息进行变更，感谢您的配合，谢谢！
 
更多备案问题请查看备案帮助
 
为了完善我们的产品及各项服务，提高您的满意度，烦请填写调查表，我们将在日后的服务中改进，感谢您的帮助
点击填写调查表
 
 
阿里云计算有限公司

**Comment by happypeter** [comment]
尊敬的用户王广忠
    ，您的ICP备案申请已通过审核，备案/许可证编号为：冀ICP备15007992号

**Comment by happypeter** [comment]
胜利！！！
