### ISSUE TITLE
卡片式教学的漂亮 html 页面

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#319]
未来也要放到好多视频网，比如 haoduoshipin.com/1000cards 下面

就是写一个脚本，把 https://gitcafe.com/happypeter/yanda/wiki 这里的简单 markdown 内容，转换成漂亮的 cards 页面。主要就是写出一个 convert.rb 文件，然后再配上一些 css

**Comment by billie66** [comment]
有道理

**Comment by billie66** [comment]
那这个页面就放在好多视频项目下吗

**Comment by happypeter** [comment]
代码先存成一个 gist 吧

**Comment by billie66** [comment]
Gitcafe 上面我的账户 billie66，添加我为 collaborator

**Comment by happypeter** [comment]
done

**Comment by billie66** [comment]
https://gist.github.com/billie66/95dbf927d3baaff34deb
