### ISSUE TITLE
search 搜索  swiftype

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#327]
https://swiftype.com/engines/hdsp

这个看上去是非常简单的。

**Comment by billie66** [comment]
先用一下 swiftype crawler 搜索，看看效果

https://swiftype.com/documentation/crawler_quick_start

不满意的话，再改 swiftype api 搜索

https://swiftype.com/documentation/overview

**Comment by billie66** [comment]
免费用户只能创建一个引擎

首先要设置搜索引擎，点击 `Install search engine` 大方块，开始配置，配置完成之后会生成所要安装的脚本代码，把代码粘贴到带有搜索框的页面中，搜索框的格式

```html
<input type="text" class="st-default-search-input">
```

虽然安装了脚本代码，但是这时还不能搜索，还需要点击激活按钮，搜索才能在网站中生效。

**Comment by billie66** [comment]
免费用户可以索引的页面数量 500 pages

https://swiftype.com/questions/swiftype-isnt-indexing-my-entire-site-how-many-pages-will-swiftype-index

**Comment by billie66** [comment]
综合一下，还是选择 swiftype api 搜索，有以下优点：

* 支持 1000 个 document（相当于数据库中的一条记录）

* 随时可以添加 document，若使用 crawler 需等待一周的时间重新索引一次

* 自定义搜索字段。crawler 借助 meta tags 也可以

**Comment by happypeter** [comment]
对，api 拥有更强的灵活性

**Comment by billie66** [comment]
document 字段类型

https://swiftype.com/documentation/tutorials/schema_design

搜索选项

https://swiftype.com/documentation/searching

Ruby on Rails demo

https://swiftype.com/documentation/tutorials/rails

**Comment by billie66** [comment]
搜索结果会返回一个 highlight 字段，给每个字段中的第一个匹配项加 <em> 标签，有点奇怪，比方说有一个 title 字段，其值为 “Rails is a web framework, rails is powerful”，若搜索 rails，则返回结果：

```
"highlight"=> {"title"=>"<em>Rails</em> is a web framework, rails is powerful"}
```

虽然 rails 有两个匹配项，但是只是高亮第一个匹配项。

**Comment by happypeter** [comment]
YC 也有一个类似的服务：http://www.algolia.com/

**Comment by billie66** [comment]
algolia 的界面看着很酷，免费版也支持 1000 个 documents

**Comment by billie66** [comment]
代码已经 push 到 github

**Comment by billie66** [comment]
创建新视频之后，会自动索引视频信息到 swifype。代码已经部署，搜索还挺快的
