### ISSUE TITLE
把 小怪兽 论坛的用户导入

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#330]
一共就20来个用户，可以手动导入。user_name, password_digest 进来。

**Comment by happypeter** [comment]
为了使用新代码，要求把目前线上的真实数据的 comments 表中添加 commentable_type ，并且把原有的 episode_id 改为 commentable_id 。 方法是这样，把老代码在本地跑起来，灌进最新的数据，然后通过下面的 migration 来实现


```
+++ b/db/migrate/20150508023913_rename_things_in_comments.rb
@@ -0,0 +1,6 @@
+class RenameThingsInComments < ActiveRecord::Migration
+  def change
+    rename_column :comments, :episode_id, :commentable_id
+    add_column :comments, :commentable_type, :string, :default => "Episode"
+  end
+end
```

**Comment by billie66** [comment]
我不知道密码怎么处理

https://gist.github.com/billie66/0dcb9d6491314b165967

**Comment by billie66** [comment]
目前，好多视频 users 这张表中，没有 password_digest 字段，而是 password_hash 和 password_salt 两个字段

**Comment by happypeter** [comment]
可能因为 好多视频 用的是老加密方式吧。没事，这个就不导入了，回头让用户重新注册吧。

**Comment by happypeter** [comment]
可能因为 好多视频 用的是老加密方式吧。没事，这个就不导入了，回头让用户重新注册吧。
