### ISSUE TITLE
下拉列表

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#343]
这个还是很有特点的。
![screen shot 2015-06-03 at 4 26 58 pm](https://cloud.githubusercontent.com/assets/72467/7974643/ad432d32-0a96-11e5-923b-83a53015b6de.png)

**Comment by happypeter** [comment]
实现一下，然后我要放到我的 toy.haoduoshipin.com/cool/list/ 中

**Comment by happypeter** [comment]
图标用 svg 吧。

**Comment by billie66** [comment]
https://www.google.com/design/icons/#ic_keyboard_arrow_down
