### ISSUE TITLE
meteor 课程

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#359]
@limingth 他们的 meteor 课程确实非常好：http://www.maiziedu.com/course/python/342-3446/

@billie66 看一下吧

**Comment by limingth** [comment]
Kevin Zhang 就是之前3月份我们在清华举办讲座时候的主讲老师，讲课确实一流。他已经在线给毛豆网培养了三期师徒班的学生了。麦子重视 buildup 课程，毛豆网更重视 connect 人。

**Comment by happypeter** [comment]
@limingth 在国内传播最先进的技术理念，确实社会意义非凡，赞！
