### ISSUE TITLE
rails api 实现前后端分离

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#360]
http://fancypixel.github.io/blog/2015/01/28/react-plus-flux-backed-by-rails-api/

**Comment by happypeter** [comment]
http://apionrails.icalialabs.com/book/chapter_nine#sec-decrement_product_quantity

**Comment by billie66** [comment]
http://tylermcginnis.com/reactjs-tutorial-a-comprehensive-guide-to-building-apps-with-react/

**Comment by happypeter** [comment]
https://www.youtube.com/watch?v=aHqnFWLP7wA 这个视频里说：

用 express.js 托管 SPA 是一种很常见的做法。

**Comment by happypeter** [comment]
https://speakerdeck.com/dfguo/reactjs-in-strikingly-1

这个 slides 里面内容很不错。

**Comment by billie66** [comment]
react router example

http://gregtrowbridge.com/using-react-router-to-match-arbitrary-urls-in-your-app/

**Comment by happypeter** [comment]
@billie66 参考上面这篇文档，和 https://github.com/happypeter/haoduoshipin/issues/360#issue-98662125 的代码，route 调通了。

**Comment by billie66** [comment]
[browsersync options](http://www.browsersync.io/docs/options/) 配置 host 选项就可以用浏览器访问虚拟机中的 react 项目了

```
host: '0.0.0.0'
```

**Comment by happypeter** [comment]
好，这个先关了吧。后续讨论到 https://github.com/happypeter/react-book

所有的重要内容都备份到了 ：https://github.com/happypeter/react-book/wiki
