### ISSUE TITLE
论坛评论模块的部分颜色不一致

### ISSUE THREAD

**Issue by lixu19941116** [happypeter/haoduoshipin#366]
<img width="235" alt="happypeter" src="https://cloud.githubusercontent.com/assets/6327995/9149356/29a39f90-3dd9-11e5-87e4-28fcf0f9dc2d.png">

.comment body:before 的 background 和 border 的颜色问题，如上图箭头指的地方所示。大图查看更为明显。

**Comment by happypeter** [comment]
的确是，感谢！
