### ISSUE TITLE
编辑视频笔记

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#367]
现在很多时候要直接在页面中编辑视频笔记，目前就是一个纯 textarea 感觉极为 shity

考虑集成一个好用的网页编辑器进来。原来用过的那个叫什么来着，cloud9 他们用的那个？

**Comment by happypeter** [comment]
是 http://ace.c9.io/ 。

@billie66 有空帮我集成进来吧。

**Comment by billie66** [comment]
下面这个 Gem 支持 rails 4.1.6

https://github.com/codykrieger/ace-rails-ap

**Comment by happypeter** [comment]
最好不要用 gem ，毕竟未来咱们要做前后端分离的。

**Comment by billie66** [comment]
ok

**Comment by billie66** [comment]
Ace 编辑器只能挂载到 div 元素，否则会报错

```javascript
ace.edit can't find div #description
```

如果网页内需要多个 Ace 编辑器，可以借鉴下面的代码

https://gist.github.com/duncansmart/5267653
