### ISSUE TITLE
用户留评论不方便

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#368]
登陆再评论的形式不太适合这种博客类的网站。还是

css-tricks 和 阮一峰博客 上的方式好。

**Comment by billie66** [comment]
本来想着使用  meteor 的 accounts-password 包提供的 Accounts.createUser() 接口保存用户信息，但这个接口只适用于用户设置密码的情况，若不提供密码则报错。

这样，我可以新创建一个 collection 名为 commenters，存储评论者的信息

**Comment by billie66** [comment]
peter 给的建议是：不需要分离用户信息，评论者的信息直接保存到 comment  document 里面
