### ISSUE TITLE
把数据库users数据导出为mongodb 格式 并且实现登陆

### ISSUE THREAD

**Issue by billie66** [happypeter/haoduoshipin#374]

**Comment by billie66** [comment]
https://www.reddit.com/r/Meteor/comments/2t1tiu/best_way_to_retrieve_data_from_rails_database/

目前 haoduoshipin 的 users 表密码加密有两个字段，password_hash 和 password_salt 

meteor 的用户密码字段是:

```js
"password": {
   "bcrypt": ""
 }
```

即使 rails 中的密码字段只有一个 password_digest，也不能直接在 meteor 中使用，所以 rails 的 users 数据不能直接导入到 meteor 的 mongodb 数据库

**Comment by happypeter** [comment]
也可以不要密码了，反正大家就是留个评论，每次都输入密码挺麻烦的。

**Comment by happypeter** [comment]
做成阮一峰博客上得那种登陆效果就可以了

**Comment by billie66** [comment]
好的
