### ISSUE TITLE
font-spider

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#375]
https://github.com/happypeter/modern-web-dev/issues/21#issuecomment-138404742

> 关于汉字字库，有这么几个：

- [有字库](http://www.youziku.com/)
- [ justfont 中文云端字型服务](http://cn.justfont.com/)
- [fonts](http://www.fonts.com/search/all-fonts?Licenses=Web&SortColumn=relevancy&searchtext=chinese&SearchType=WebFonts&page=1&itemsPerPage=10&LanguageExtension=Simplified+Chinese)
- [易字云](http://yun.zitiguanjia.com/)
- [iFontCloud](http://webfont.arphic.com/index/index.jsp?lang=zh&country=CN)

>比较有名的还是前两个 **有字库** 和 **justfont**

**Comment by happypeter** [comment]
这个可以录制一期视频了。

**Comment by billie66** [comment]
justfont 诞生于台湾，目标是设计出具有台湾本土气息的字体，下面是 justfont 制作的一个记录片，如何设计字体

https://www.youtube.com/watch?v=ON_ADrrLkqk&feature=youtu.be

**Comment by billie66** [comment]
codepen demo

http://codepen.io/billie66/pen/wKyvRN#0

**Comment by billie66** [comment]
网页字体优化

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=zh-cn

**Comment by happypeter** [comment]
嗯，这是非常好的进阶学习内容，要强力推荐给大家。
