### ISSUE TITLE
备案两个域名

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#392]
http://duopingshidai.com/

描述：响应式设计资料分享网站。

http://www.bianguaishou.com/

描述：《小白变怪兽》web 开发基础知识分享网站。

这两个网站目前都已经指向了阿里云。但是没有备案不能用。（描述中不能有：官网，视频 等字样）

**Comment by happypeter** [comment]
考虑放到 digitalocean 服务器，但是 ssh haoqicat.com 居然经常连不上。

所以还是要费力备案了。

**Comment by happypeter** [comment]
aliyun 的短信：

>初审通过，请拍照上传

**Comment by happypeter** [comment]
# again

aliyun 的短信：

> 照片审核已经通过

**Comment by happypeter** [comment]
aliyun 的短信：

> 已经提交信管局审核，通过会有短信通知

**Comment by happypeter** [comment]
尊敬的王广忠：
 
	恭喜您，您的备案已经办理成功！
王广忠的备案（订单号：21320218376）已经通过省通信管理局审核！
请登录阿里云代备案系统查看您的备案号，并请您按照工信部规定，在您的网站首页底部中间位置，放置您的备案号并链接至"http://www.miitbeian.gov.cn/"。例如"京ICP备999999"（此备案号为例子，请您一定更换成自己的备案号）。
附工信部备案规定：非经营性互联网信息服务提供者应当在其网站开通时，在主页底部的中央位置标明其备案编号，并在备案编号下方按要求链接信息产业部备案管理系统网址，供公众查询核对。
 
备案成功后，您还可以：
1.增加新网站，登录阿里云代备案系统，在已成功备案信息下增加新的网站;
2.单位/个人信息或网站发生了变化，及时登录阿里云代备案系统，提交变更备案信息;
 
相关政策法规： 依据《非经营性互联网信息服务备案管理办法》第二十三条规定，如备案信息不真实，将关闭网站并注销备案。若您的备案信息发生变更，请您尽快将备案信息进行变更，感谢您的配合，谢谢！
 
更多备案问题请查看备案帮助
 
为了完善我们的产品及各项服务，提高您的满意度，烦请填写调查表，我们将在日后的服务中改进，感谢您的帮助
点击填写调查表
 	/tr>
温馨提示：如果您的网站后续有支付、收款类的需求，您可以通过 支付宝-商家服务 进行了解或直接选购合作产品。
 
 
阿里云计算有限公司

**Comment by happypeter** [comment]
https://mail.google.com/mail/u/0/#inbox/1506fa0dbf629632

**Comment by billie66** [comment]
good

**Comment by happypeter** [comment]
@billie66 看一下备案号是多少？

**Comment by billie66** [comment]
冀ICP备15007992号-2

**Comment by happypeter** [comment]
两个域名的备案号是同一个吗？

**Comment by billie66** [comment]
不是，第一个是

冀ICP备15007992号-1
