### ISSUE TITLE
网站改成静态的

### ISSUE THREAD

**Issue by billie66** [happypeter/haoduoshipin#394]
- tag 功能不要了，因为可以总结为 bianguaishou.com 这样的课程来分享
- /all /about 等其他页面基本都可以是静态的
- 评论功能暂时感觉意义不大，未来如果必要可以通过 api 形式来集成
- wechat 是不可忽略了，wechat 中也可以评论的

**Comment by happypeter** [comment]
https://github.com/happypeter/haoduoshipin/issues/395

**Comment by billie66** [comment]
http://hdsp.haoduoshipin.com
