### ISSUE TITLE
关于服务器端部署的问题

### ISSUE THREAD

**Issue by Wellaiyo** [happypeter/haoduoshipin#401]
@happypeter 
我想在一台服务器上部署多个网站，一开始打算的是利用隐形url来实现，监听不同端口，但是弄出来的网站代码中会自带frameset，这不是我想要的。
请教大牛，What should I do?

**Comment by happypeter** [comment]
http://www.bianguaishou.com/#ubuntu-nginx

nginx 设置多个 server 就行

**Comment by Wellaiyo** [comment]
Thanks , 终于明白了 nginx代理 的原理了
