### ISSUE TITLE
网站大改版

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#414]
- 把 /all 放到首页
- 首页上那些过时的 Imooc 课程链接都去掉，改成一个 haoqicat.com 链接即可
- 放弃 meteor
- 放弃后台评论、登录等功能
- 一个 react 前台，读取 json 数据即可

**Comment by shaohailong** [comment]
HI peter 为何要放弃 meteor 呢

**Comment by happypeter** [comment]
不算放弃，是暂时离开一下。meteor 目前发展的还不是很成熟，网上的资料也没有 react+express 这套方案多。

**Comment by shaohailong** [comment]
搜噶. express 支持 订阅发布的模式 (DDP) 么?

**Comment by shaohailong** [comment]
另外. 我们一个项目. 打算使用 meteor 做后台, 利用DDP来简化开发流程, 至于一些meteor 无法支持的(文档不全) 的功能, 我们打算使用 java 提供相关服务.  peter 你看可行性如何.

**Comment by happypeter** [comment]
express 配合 socket.io 肯定能搭建起类似 DDP 的效果的，不过可能有点麻烦。如果真的需要用 DDP ，那直接使用 meteor 应该是不错的选择。

**Comment by shaohailong** [comment]
恩， 回头研究研究 socket.io， 应该是个好东东。 ：p
