### ISSUE TITLE
网站搜索和 SEO

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#415]
- 搜索就用 http://www.ruanyifeng.com/blog/2016/11/byte-order.html 这里的百度站内
- 放弃 meteor/react ，改用 gulp，输入文件 doc/204-es6.md 输出 dist/204.html

**Comment by happypeter** [comment]
目前完成的功能效果，是这样实现的：

- 首页添加一个指向 /search.html 页面的搜索框
- search.html 页面中采用“嵌入式”的页面展示效果

**Comment by happypeter** [comment]
网站上线一天多了，还是搜不到 haoduoshipin.com 主站的内容，只能搜到一些 boo.haoduoshipin.com 的老内容

**Comment by happypeter** [comment]
s三天了，还是搜不到

**Comment by happypeter** [comment]
谷歌现在已经能搜到 haoduoshipin.com 了，百度还不行

**Comment by happypeter** [comment]
可以自己提交种子 URL 的，帮助文档里有具体方式，我提交了

haoduoshipin.com 


目前只能搜出一个页面来 http://haoduoshipin.com/v/37

**Comment by happypeter** [comment]
嗯，还是不行，搜不到

**Comment by billie66** [comment]
提交了网页列表，生效时间1-2天

**Comment by happypeter** [comment]
提交的方式是什么？写了了脚本生成了一个 sitemap ？

**Comment by billie66** [comment]
直接在网站上添加了一个 sitemap 文件，然后百度搜索设置中指定 sitemap 文件的路径就行了

**Comment by happypeter** [comment]
生成 sitemap 文件是怎么操作的？是不是用了一个脚本？贴到这里吧

**Comment by billie66** [comment]
百度搜索终于生效了，还有一个问题是，搜索结果的每条记录的标题都是 `haoduoshipin`，所以还得把每个页面的标题信息修改一下

**Comment by happypeter** [comment]
嗯嗯，厉害厉害。

sitmap.txt 要存放到哪里？

**Comment by billie66** [comment]
是 sitemap.xml 文件，放到项目根目录下

**Comment by happypeter** [comment]
嗯，的确

```
peter@fire:~/haoduo-dist$ ls
css  index.html  search.html  sitemap.txt  sitemap.xml  v
peter@fire:~/haoduo-dist$
```

上面的 sitemap.txt 直接删除就可以了。

**Comment by happypeter** [comment]
最新发布的几篇文章搜不到，所以我更新了一下 sitemap.xml ，看看几天后能搜到。

用这个 http://haoduoshipin.com/search.html?q=markdown

搜 208.html 试试
