### ISSUE TITLE
http://haoduoshipin.com/ 中部分视频失效

### ISSUE THREAD

**Issue by note286** [happypeter/haoduoshipin#419]
>http://haoduo-1253322599.costj.myqcloud.com/115-getting-git-part2.mp4
>http://haoduo-1253322599.costj.myqcloud.com/116-getting-git-part3.mp4
>http://haoduo-1253322599.costj.myqcloud.com/118-install-chrome-first-html.mp4
>http://haoduo-1253322599.costj.myqcloud.com/120-block-inline.mp4
>http://haoduo-1253322599.costj.myqcloud.com/134-position.mp4
>http://haoduo-1253322599.costj.myqcloud.com/192-modern-dev-qa-p2.mp4

这六个视频无法观看和下载，求问是什么原因呢？是过时了吗还是？？？

**Comment by happypeter** [comment]
115-fixed
116-fixed
118-fixed
120-fixed
134-fixed
192-fixed

现在都修复了
