### ISSUE TITLE
使用真正的 json 格式

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#425]
https://github.com/happypeter/haoduoshipin/blob/master/data/index.json

这个文件目前不是  json 格式：最外层没有 `{}` 

这个需要修正一下，跟标准做法统一。

**Comment by billie66** [comment]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON
数组形式的JSON数据也是合法的
