### ISSUE TITLE
视频详情页打开等待时的 spinner

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#426]
由于是 ssr ，所以用户点列表上的一个视频之后，需要等待好几秒，才能打开视频详情页。

这个看看如何能加一个 spinner 。跟客户端渲染情况不同，这个 spinner 不是出现在 v/123 页面上，而是出现在首页上。

**Comment by billie66** [comment]
根据该讨论添加了加载特效 https://github.com/zeit/next.js/issues/1806
