### ISSUE TITLE
 使用 gatsby 重写网站

### ISSUE THREAD

**Issue by billie66** [happypeter/haoduoshipin#429]
https://github.com/gatsbyjs/gatsby

**Comment by happypeter** [comment]
这部分咱们首先要攻克的是：

- 没有数据输入源头，也就是没有 markdown 或者 api 请求的情况下，如何创建网站
  - 这样我估计能避开 graphQL 和其他一些复杂的步骤
- 先把上面的任务解决了，然后下一步再继续考虑 API 的相关问题

如果后续要把这些知识做成课程，也会是按照上面的由简入繁的思路。

**Comment by billie66** [comment]
可以只用静态数据构建两个页面

**Comment by happypeter** [comment]
- 第一步，先做没有任何数据的页面，也就是如何用 Gatsby 做一个纯展示性的单个网页
- 后续，再去考虑有数据的情况

**Comment by billie66** [comment]
https://github.com/billie66/gatsby-demo

**Comment by happypeter** [comment]
OK

**Comment by happypeter** [comment]
关于文字稿的书写规范，参考：https://github.com/happypeter/onestep/wiki/shownotes-howto

**Comment by happypeter** [comment]
新项目以及上线了。
